### ISSUE TITLE
田中君

### ISSUE THREAD

**Issue by hanabonbon** [sisutemukaihatu/tabetter#142]
投稿に画像がない場合の処理を記述

投稿に日付をもたせる（タイムラインとデザインは統一）

リプライ機能は実装しない。代わりにコメント欄をスレッド形式で表示

コメント表示はcommentidの降順

メンション機能を実装→投稿詳細にいるユーザーのidをセレクトボックスに入れる→コメント送信画面でセレクトボックスでユーザーを選べるようにしてほしい

![MicrosoftTeams-image (1)](https://github.com/sisutemukaihatu/tabetter/assets/107159047/32e11f9e-69a0-49b3-bc1a-a1bdd3fcc473)

**Comment by 1GiTHuB9** [comment]
完了しました
