### ISSUE TITLE
oyamada

### ISSUE THREAD

**Issue by oyamada-jin** [sisutemukaihatu/tabetter#163]
task

profilecheckのようなスタイルにする

アラートスタイル変更

commentcheck.php　完了

forum_commentCheck.php　完了

forumCheck.php　完了

postCheck.php　多分完了　timeline投稿画面移れたら確認する

postImageCheck.php　多分完了　timeline投稿画面移れたら確認する

signUpIdMsg.php　アラートいらないと思う

sigunUpMsg.php　アラートいらないと思う

**Comment by hanabonbon** [comment]
OK!
