### ISSUE TITLE
ログイン画面の配置

### ISSUE THREAD

**Issue by 1GiTHuB9** [sisutemukaihatu/tabetter#55]
ロゴのせいか、横幅を小さくすると左寄りになります　どうしたらいいと思いますか？
![image](https://github.com/sisutemukaihatu/tabetter/assets/115598038/66b51e57-19a8-41b2-8553-b65c60b514e9)

**Comment by 1GiTHuB9** [comment]
それと、画像がかぶってメールアドレスのフォームが選択できません

**Comment by 1GiTHuB9** [comment]
> それと、画像がかぶってメールアドレスのフォームが選択できません

これは解決しました

**Comment by hanabonbon** [comment]
コードを確認しないと分からないです

**Comment by 1GiTHuB9** [comment]
ロゴ画像のサイズが大きいことが原因でした。サイズを小さくしたら解決しました。
