### ISSUE TITLE
初期アイコンをデータベースに保存する処理が上手くいかない

### ISSUE THREAD

**Issue by hanabonbon** [sisutemukaihatu/tabetter#87]
代替案としてプロフィール画面でif文を使って初期アイコンとユーザーが設定したアイコンの表示を分けるというのはどうでしょうか。例: if(profile_imageがnullではない){ <アイコンを表示> }else{ <初期アイコンを表示>}

**Comment by oyamada-jin** [comment]
いいと思います

**Comment by hanabonbon** [comment]
新規登録時に画像を保存してもらうよう変更しました
